version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wb_aggregator
      POSTGRES_USER: socialist
      POSTGRES_PASSWORD: revolution2023
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U socialist -d wb_aggregator"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  backend:
    build: ./admin/backend
    environment:
      DATABASE_URL: postgresql+asyncpg://socialist:revolution2023@postgres:5432/wb_aggregator
      BOT_TOKEN: 7205892472:AAGAShZUu-DiXSIYhW7_GSCwZIq-pVT3cNc
      TELEGRAM_WEBAPP_URL: https://develooper.ru
      DEVELOPMENT_MODE: "False"
      BOT_API_URL: http://bot:8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./admin/frontend
    environment:
      VITE_API_URL: https://develooper.ru/api
    volumes:
      - ./admin/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-data:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - frontend-network

  bot:
    build: ./admin/bot
    environment:
      TELEGRAM_BOT_TOKEN: 7205892472:AAGAShZUu-DiXSIYhW7_GSCwZIq-pVT3cNc
      WEBAPP_URL: https://develooper.ru
    networks:
      - backend-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-data:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d develooper.ru

volumes:
  postgres_data:
  certbot-data:
  certbot-www:

networks:
  backend-network:
  frontend-network: 