services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wb_aggregator
      POSTGRES_USER: socialist
      POSTGRES_PASSWORD: revolution2023
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U socialist -d wb_aggregator" ]
    networks:
      - backend-network

  backend:
    build: ./admin/backend
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - TELEGRAM_WEBAPP_URL
      - BOT_API_URL
      - TELEGRAM_BOT_TOKEN
      - SUPER_ADMIN_IDS
      - DEVELOPMENT_MODE
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network
      - frontend-network

  frontend:
    build:
      context: ./admin/frontend

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./uploads:/usr/share/nginx/html/uploads:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - frontend-network
    env_file:
      - .env

  bot:
    build: ./admin/bot
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_WEBAPP_URL
      - DATABASE_URL
      - API_URL
      - SUPER_ADMIN_IDS
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
  frontend-network:
