version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wb_aggregator
      POSTGRES_USER: socialist
      POSTGRES_PASSWORD: revolution2023
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U socialist -d wb_aggregator"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  backend:
    build: ./admin/backend
    environment:
      DATABASE_URL: postgresql+asyncpg://socialist:revolution2023@postgres:5432/wb_aggregator
      BOT_TOKEN: 7205892472:AAGAShZUu-DiXSIYhW7_GSCwZIq-pVT3cNc
      TELEGRAM_WEBAPP_URL: libertylib.online
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./admin/frontend
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: https://libertylib.online/api
    depends_on:
      - backend
    networks:
      - frontend-network
      - backend-network

  bot:
    build: ./admin/bot
    environment:
      BOT_TOKEN: 7205892472:AAGAShZUu-DiXSIYhW7_GSCwZIq-pVT3cNc
      WEBAPP_URL: https://libertylib.online
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
  frontend-network: 